permalink: none
title: Meteor Kaiso
safe: true
lsi: false
markdown: redcarpet
pygments: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

url: http://127.0.0.1:4000/meteor_jp
